WORKFLOW_STEPS = [
    "dataset_loading",
    "schema_detection",
    "data_cleaning",
    "type_inference",
    "missing_value_analysis",
    "relationship_discovery",
    "statistical_analysis",
    "anomaly_detection",
    "driver_analysis",
    "quality_scoring",
    "schema_drift_check",
    "chart_generation",
    "insight_extraction",
    "excel_report_creation",
    "final_export",
]
